apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.kubevirt.io/rhel8.5: Red Hat Enterprise Linux 8.0 or higher
  labels:
    app: rhel8-vm-test1
    flavor.template.kubevirt.io/small: "true"
    os.template.kubevirt.io/rhel8.5: "true"
    vm.kubevirt.io/template: rhel8-server-small
    workload.template.kubevirt.io/server: "true"
  name: rhel8-vm-test1
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: rhel8-vm-test1
    spec:
      sourceRef:
        kind: DataSource
        name: rhel8
        namespace: openshift-virtualization-os-images
      storage:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: "32212254720"
        storageClassName: ocs-storagecluster-ceph-rbd
        volumeMode: Block
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      labels:
        flavor.template.kubevirt.io/small: "true"
        kubevirt.io/domain: rhel8-vm-test1
        kubevirt.io/size: small
        os.template.kubevirt.io/rhel8.5: "true"
        vm.kubevirt.io/name: rhel8-vm-test1
        workload.template.kubevirt.io/server: "true"
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rhel8-vm-test1
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      hostname: rhel8-vm-test1
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: rhel8-vm-test1
        name: rhel8-vm-test1
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: cloud-user
            password: password
            chpasswd: { expire: False }
        name: cloudinitdisk
